apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Values.name }}" 
  ports:
      port: 8000
      protocol: TCP
      targetPort: 8000
