apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: "{{ .Values.name }}" 
  ports:
    - nodePort: 30088
      port: 8000
      protocol: TCP
      targetPort: 8000
